{
 "title": "My Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU% Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{node=\"ip-10-0-101-12.ec2.internal\", mode=\"idle\"}[10m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{node=\"ip-10-0-101-12.ec2.internal\"} / 1048576",
     "legendFormat": "\"Free Memory\""
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=\"ip-10-0-101-12.ec2.internal\"} / 1048576",
     "legendFormat": "\"Total Memory\""
    },
    {
     "expr": "node_memory_Cached_bytes{node=\"ip-10-0-101-12.ec2.internal\"} / 1048576",
     "legendFormat": "\"Buffer/Cache\""
    }
   ]
  },
  {
   "title": "Node Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_disk_io_time_seconds_total{node=\"ip-10-0-101-12.ec2.internal\", device=\"nvme0n1\"}",
     "legendFormat": "EC2 Root"
    },
    {
     "expr": "node_disk_io_time_seconds_total{node=\"ip-10-0-101-12.ec2.internal\", device=\"nvme1n1\"}",
     "legendFormat": "Prometheus EBS"
    }
   ]
  }
 ]
}